name: Docker Login Test

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
