name: CI/CD Docker Push

on:
  push:
    branches: [ main ]  # Triggers only on main branch pushes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend

    - name: Build and push API Gateway
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway ./api-gateway
        docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway

    - name: Build and push Product Service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service ./product-service
        docker push ${{ secrets.DOCKER_USERNAME }}/product-service
