name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway ./api-gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service ./product-service
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service

      # (Optional) Apply to remote cluster using kubectl + kubeconfig
