- name: Set Kubeconfig
  run: |
    mkdir -p $HOME/.kube
    echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
    chmod 600 $HOME/.kube/config

- name: Deploy to Kubernetes
  run: kubectl apply -f k8s-manifests/
